from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from datetime import datetime


def generate_pdf(path, ward, prediction):
    doc = SimpleDocTemplate(path, pagesize=A4)
    styles = getSampleStyleSheet()

    # ---- Custom styles ----
    title_style = ParagraphStyle(
        name="Title",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        textColor=colors.darkblue
    )

    section_style = ParagraphStyle(
        name="Section",
        parent=styles["Heading2"],
        textColor=colors.darkgreen
    )

    normal = styles["Normal"]

    elements = []

    # ---- Title ----
    elements.append(Paragraph("Smart Community Health Monitoring Report", title_style))
    elements.append(Spacer(1, 20))

    # ---- Subtitle ----
    elements.append(Paragraph(
        f"Generated on: {datetime.now().strftime('%d %B %Y, %H:%M')}",
        normal
    ))
    elements.append(Spacer(1, 20))

    # ---- Section Header ----
    elements.append(Paragraph("Ward Risk Summary", section_style))
    elements.append(Spacer(1, 10))

    # ---- Data Table ----
    data = [
        ["Parameter", "Value"],
        ["Ward", ward],
        ["Predicted Risk Level", prediction],
        ["System", "AI Early Warning Engine"],
        ["Location", "Coimbatore Smart Health Grid"]
    ]

    table = Table(data, colWidths=[200, 300])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("GRID", (0,0), (-1,-1), 1, colors.grey),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.whitesmoke, colors.lightgrey]),
        ("PADDING", (0,0), (-1,-1), 8)
    ]))

    elements.append(table)
    elements.append(Spacer(1, 30))

    # ---- Explanation Section ----
    elements.append(Paragraph("AI Interpretation", section_style))
    elements.append(Spacer(1, 10))

    if prediction == "High":
        msg = "High outbreak risk detected. Immediate monitoring and intervention recommended."
    elif prediction == "Medium":
        msg = "Moderate risk observed. Preventive actions advised."
    else:
        msg = "Low risk. Conditions stable but continued monitoring suggested."

    elements.append(Paragraph(msg, normal))
    elements.append(Spacer(1, 40))

    # ---- Footer ----
    footer = Paragraph(
        "Generated by Smart Community Health Monitoring System",
        ParagraphStyle(name="footer", alignment=TA_CENTER, textColor=colors.grey)
    )
    elements.append(footer)

    # ---- Build PDF ----
    doc.build(elements)